"""Section 13/14 — component-by-component comparison DGE vs Vāgdhenu vs what Kamadhenu needs, with the fixed
status vocabulary, evidence paths, what is missing and the exact next action. Statuses that depend on measured
data are computed; the rest are inspection results recorded here with their evidence."""
from .common import DS, write_json, read_json, write_csv, write_text, html_page, table_html, esc, log, now_ist, DONE, VERIFIED, PARTIAL, IN_PROGRESS, NOT_STARTED, BLOCKED, NOT_REQUIRED


def run():
    inv = read_json(DS / "audio_inventory.json", {"summary": {}}); mp = read_json(DS / "audio_text_mapping.json", {"summary": {}})
    rb = read_json(DS / "reference_bank.json", {"summary": {}}); cov = read_json(DS / "chandas_coverage.json", {"summary": {}}); ext = read_json(DS / "external_audio_sources.json", {"totals": {}})
    fg = read_json(DS / "frontend_gap_report.json", {"findings": []}); cmp = read_json(DS / "chandas_comparison.json", {})
    n_files = inv.get("summary", {}).get("files", 0); n_hi = mp.get("summary", {}).get("bands", {}).get("1.00 exact", 0) + mp.get("summary", {}).get("bands", {}).get("0.90–0.99 very strong", 0)
    n_ref = rb.get("summary", {}).get("metres_safe_reference", 0); n_ver = rb.get("summary", {}).get("metres_human_verified", 0)
    rows = [
        dict(component="Sanskrit normalization", dge="clean_devanagari + search_toolkit folds (search-grade, lossy on purpose)", vagdhenu="prep_text.strip_punct/to_deva + tts_normalize (visarga/anusvāra rewrites)", required="lossless Devanagari→SLP1 with Vedic-ext support, Kannada input, no search folds",
             status=PARTIAL, evidence="frontend_gap_report.json: 22 cases; jihvāmūlīya/upadhmānīya dropped by DGE to_slp1, ZWJ leaks", path="dge/search_toolkit_pkg/, tools/kamadhenu/texts.py", missing="one Kamadhenu normaliser with explicit, logged transforms", next="port the 4 Vāgdhenu fixes (ᳵ/ᳶ, ZW strip, ṝ→rū option, parenthetical strip) into tools/kamadhenu/texts.py and unit-test them"),
        dict(component="G2P", dge="none (SLP1 = phonemic)", vagdhenu="tts_g2p.to_slp1 (+Z/V/y~/| extensions); production feeds Kannada script to IndicF5", required="SLP1 with Vedic extensions; script-routing decision per model",
             status=PARTIAL, evidence="frontend_gap_report.json findings 'G2P'", path="vagdhenu/src/tts_g2p.py", missing="decision on Devanagari vs Kannada routing for the lead's voice", next="A/B on 20 rendered verses once a voice exists (Stage 2)"),
        dict(component="syllabification", dge="chandas.js syllabify (browser JS, Devanagari only; candrabindu/ᳵ not guru)", vagdhenu="tts_syllabify.py (maximize-onset) + chandas_labeler.syllabify_slp1 (orthographic)", required="one akṣara segmenter agreeing with DGE Chandas",
             status=PARTIAL, evidence="chandas_runner.js runs the DGE engine headlessly over 7,696 units; 2 engine bugs found", path="tools/kamadhenu/chandas_runner.js, dge/js/chandas.js:58", missing="fix candrabindu + ᳵ/ᳶ weight in chandas.js; Kannada input", next="patch dge/js/chandas.js nasal test to /[ँंःᳵᳶ]/ and add a test"),
        dict(component="Chandas", dge="245 vṛttas + 10 mātrā + anuṣṭubh rule; sama/ardhasama/upajāti/viṣama/mātrā", vagdhenu="13 metres (tts_meter) / 10 signatures (chandas_labeler); 4 patterns WRONG; two tables disagree", required="ONE authoritative layer = DGE",
             status=PARTIAL, evidence=f"chandas_comparison.json: {len(cmp.get('disagreements_with_dge', []))} Vāgdhenu patterns disagree with DGE; {cov.get('summary',{}).get('metres_in_dge_db',0)} DGE metres", path="dge/data/vedanga/chandas/data.json, tools/kamadhenu/compare_vagdhenu.py", missing="DGE: strict anuṣṭubh (vipulā → अज्ञातम्), upajāti table missing U-I-U-U, no Kannada input; 44% of corpus units unresolved", next="extend chandas.js: vipulā classes + generic indra/upendra mix; fix ऋद्धि row in data.json"),
        dict(component="Laghu/Guru", dge="chandas.js pattern (ग/ल)", vagdhenu="tts_weight.tag_weights + chandas_labeler.scan (L/G)", required="per-akṣara L/G from DGE", status=DONE, evidence="text_index.json chandas_analysis.laghu_guru for every unit; agrees with Vāgdhenu on 18/24 templates (the 6 differ only where Vāgdhenu is wrong or the metre is upajāti)", path="tools/kamadhenu/chandas_bridge.py", missing="nothing for dataset stage", next="—"),
        dict(component="Gaṇa", dge="chandas.js ganas() (य म त र ज भ न स)", vagdhenu="none explicit (uses L/G ids)", required="gaṇa string per pāda", status=DONE, evidence="chandas_analysis.gana populated", path="dge/js/chandas.js:85-91", missing="—", next="—"),
        dict(component="reference bank", dge="none (ARCHITECTURE.md §MVP-5 plan only)", vagdhenu="bank.json + 27 wavs, 16 metres, Prathosh's voice, half-reference rule", required="per-metre clean references in the lead's voice, human-verified text=audio",
             status=PARTIAL if n_ref else NOT_STARTED, evidence=f"reference_bank.json: {n_ref} metres with a structurally safe candidate, {n_ver} human-verified", path="kamadhenu_dataset/reference_bank.html", missing="human listen-check on every candidate; clean 24 kHz+ takes for metres with only low-rate audio", next="open reference_bank.html, verify the P0 metres, add mapping_overrides.json verified:true"),
        dict(component="speaker voice", dge="none", vagdhenu="Prathosh (production) + pilot reciter; voice-steer fine-tune", required="the lead's (or designated reciter's) voice, ≥1–3 h clean", status=BLOCKED, evidence="no speaker metadata in any source; recordings are unattributed; no TTS-grade (48 kHz/24-bit) audio exists anywhere in DGE", path="dataset_health_report.json speaker_count", missing="who is the Kamadhenu voice? consent + recording protocol", next="lead decides the voice; then record per RECORDING_REQUESTS.csv P0"),
        dict(component="training data", dge="0 h in repo (2 orphan files); ~1,000 SMV clips at 11 kHz/16 kbps on the audio-data repo", vagdhenu="3.02 h Prathosh + 5 h pilot (not shared)", required="≥1 h clean single-speaker aligned pairs for adaptation",
             status=PARTIAL if n_files else NOT_STARTED, evidence=f"audio_inventory.json: {n_files} files, {inv.get('summary',{}).get('total_duration_seconds',0)/3600:.1f} h fetched; {n_hi} high-confidence mappings; grades {inv.get('summary',{}).get('by_grade',{})}", path="kamadhenu_dataset/metadata.jsonl, subsets/", missing="verified text=audio; speaker attribution; most audio is lossy/low-rate", next="run the review queue; decide which speaker's clips count"),
        dict(component="fine tuning", dge="none", vagdhenu="training/finetune_indicf5.py, phase2_finetune.py, bigvgan_vocoder_train.py (CUDA 12.1, models ~3.15 GB)", required="IndicF5 adaptation on the Kamadhenu set", status=NOT_STARTED, evidence="no GPU here; Vāgdhenu scripts reference private paths (<REPO>/<PROD>)", path="vagdhenu/training/", missing="GPU host, cleaned dataset, weights download (HF prathoshap/vagdhenu)", next="do NOT start until dataset_verified ≥ 30 min of grade A/B audio"),
        dict(component="prosody", dge="planned (ARCHITECTURE.md §4)", vagdhenu="reference-driven only; text-side conditioner proven inert (TECH_REPORT §14); extract_prosody.py bank", required="reference-driven first; explicit control later", status=NOT_STARTED, evidence="TECH_REPORT.md §14, gana_uni.py", path="vagdhenu/src/extract_prosody.py", missing="prosody bank from the lead's recordings (needs MFA alignment)", next="Stage 4 — after Stage 2 voice exists"),
        dict(component="duration control", dge="none", vagdhenu="fix_duration = ref_len + n_syll × sec_per_syll (bank.json per metre)", required="per-metre sec/syllable measured from the lead's recordings", status=PARTIAL, evidence="mapping.py uses Vāgdhenu's 0.26–0.44 s/syll band for plausibility; the lead's actual pace is unmeasured", path="tools/kamadhenu/mapping.py SEC_PER_SYL", missing="measured sec/syll per metre from verified clips", next="compute from dataset_verified once ≥5 clips/metre are verified"),
        dict(component="Vedic svara", dge="Vedic corpus present; accent marks stripped by all text paths", vagdhenu="out of scope (classical chant only)", required="separate annotation + recording track (Stage 6)", status=NOT_STARTED, evidence="frontend_gap_report.json 'Vedic svara' finding; dge/veda_toolkit/superseded/05_chandas_autodetect_FAILED.py", path="dge/tts/ARCHITECTURE.md §Vedic", missing="everything", next="do not start"),
        dict(component="inference", dge="none", vagdhenu="render.py / render_core.py / render_production.py (F5 + BigVGAN, CUDA)", required="render DGE text via Vāgdhenu with a Kamadhenu reference", status=NOT_STARTED, evidence="no GPU; weights not downloaded; examples/sample_shard.json shows the input shape {id, meter, padas[], seed, out}", path="vagdhenu/src/render.py", missing="GPU host + weights", next="first render = 5 verses with Vāgdhenu's own bank to establish the baseline (Stage 1)"),
        dict(component="audio QC", dge="audio-detect.js (browser boundary detection); tools/audio_admin (Demucs, needs torch)", vagdhenu="MFA gates dropped; duration gate kept", required="format/level/silence/clipping/duplicate QC + duration gate", status=DONE, evidence=f"inventory.py measured {n_files} files: flags {inv.get('summary',{}).get('flags',{})}", path="tools/kamadhenu/inventory.py, audio_inventory.json", missing="LUFS (RMS used), no ASR check", next="add ASR verification (IndicConformer ONNX, CPU) as P1 engineering"),
        dict(component="production rendering", dge="none", vagdhenu="render_batch / 4-GPU fan-out / swap_shloka (MBTN shipped 17 h 34 m)", required="batch render per grantha with per-verse outputs", status=NOT_STARTED, evidence="TECH_REPORT.md §11, §15", path="vagdhenu/src/render_production.py", missing="everything upstream", next="—"),
        dict(component="CDN/storage", dge="jsDelivr over bhumandala-audio-data + archive.org, base-URL override chain in config.js", vagdhenu="local/YouTube", required="object store per ARCHITECTURE.md §storage; keep DGE's URL convention", status=DONE, evidence="1,042 SMV files served from the audio-data repo; 5 verse links 404 (fetch_manifest.json failed)", path="dge/js/config.js:485-508, dge/js/audio.js:66-72", missing="fix 5 broken links; decide storage for TTS output", next="upload smv5.8/5.14/5.16 + rv02.54/rv10.06 or unlink them"),
        dict(component="player integration", dge="audio.js v3.1 (speed memory, resume, offline cache, estimated word sync)", vagdhenu="karaoke video assembly (MBTN)", required="per-verse audio + akṣara timing JSON (ARCHITECTURE.md §player)", status=PARTIAL, evidence="dge/js/audio.js:585-592 says word sync is an estimate; no timing JSON exists", path="dge/js/audio.js", missing="timing data (needs forced alignment)", next="after Stage 1 renders exist"),
    ]
    for r in rows:
        r["required_for_kamadhenu"] = r.pop("required"); r["file_or_path"] = r.pop("path"); r["what_is_missing"] = r.pop("missing"); r["exact_next_action"] = r.pop("next")
    write_csv(DS / "kamadhenu_gap_matrix.csv", rows, ["component", "dge", "vagdhenu", "required_for_kamadhenu", "status", "evidence", "file_or_path", "what_is_missing", "exact_next_action"])
    write_json(DS / "kamadhenu_gap_matrix.json", {"generated_at": now_ist(), "rows": rows})
    from collections import Counter
    c = Counter(r["status"] for r in rows)
    body = ["<div class='cards'>"] + [f"<div class='card'><b>{v}</b><span>{esc(k)}</span></div>" for k, v in c.items()] + ["</div>",
            table_html(rows, ["component", "dge", "vagdhenu", "required_for_kamadhenu", "status", "evidence", "file_or_path", "what_is_missing", "exact_next_action"], mono_fields=("file_or_path",))]
    write_text(DS / "kamadhenu_gap_matrix.html", html_page("Kamadhenu — component gap matrix", "".join(body), "Component | DGE | Vāgdhenu | Required for Kamadhenu | Status"))
    log(f"gap matrix: {dict(c)}")
    return rows


if __name__ == "__main__":
    run()
