"""GRETIL importer for the Darśana branch (Nyāya, Vaiśeṣika, Mīmāṃsā).

Kept separate from importers/gretil.py because the śāstra texts are structurally
unlike the smṛti/kāvya ones that module handles. Those are verse corpora with a
'// ABBR_canto.verse //' marker on every śloka. Nyāya and Mīmāṃsā are prose:
sūtra + bhāṣya + vārttika running together, segmented by section headings
(adhikaraṇa, āhnika, stabaka, adhyāya-pāda) rather than by verse number. So the
unit here is a SECTION, not a verse, and the parser is heading-driven.

Targets are the layer folders generated by tools/darshanas/scaffold_darshanas.py.
The scaffolder must have run first — this importer fills stubs, it does not
create them.

GRETIL is romanised IAST, not Devanagari; transliteration is a pipeline step
(common.iast_to_dev). Every file carries "COPYRIGHT AND TERMS OF USAGE AS FOR
SOURCE FILE", so the header's source-attribution block is captured verbatim into
source_note rather than discarded.

Run:  python importers/dispatch.py <id>
      python importers/darshana_gretil.py --list
"""

import html
import re
import sys

from common import http_get, to_text, iast_to_dev, itrans_to_iast, write_grantha

BASE = "https://gretil.sub.uni-goettingen.de/gretil/"

# id -> spec. `target` is a path under dge/data/ produced by the scaffolder.
DARSHANA_GRETIL = {
    "nyayasutra_bhashya": dict(
        name="Nyāyasūtra with Vātsyāyana's Bhāṣya",
        author="पक्षिलस्वामिवात्स्यायनः",
        schema="grantha_tika_text",
        tika_title="न्यायभाष्यम्",
        target="darshana/nyaya/prachina_nyaya/nyaya_sutra/bhashya_vatsyayana",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/nysvbh1u.htm"]),

    "nyayasutra_tatparyatika": dict(
        name="Nyāyasūtra with Vācaspati Miśra's Tātparyaṭīkā",
        author="वाचस्पतिमिश्रः",
        schema="grantha_tika_text",
        tika_title="न्यायवार्त्तिकतात्पर्यटीका",
        target="darshana/nyaya/prachina_nyaya/nyaya_sutra/tatparya_tika",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/nystik_u.htm"]),

    "tarkasangraha_mula": dict(
        name="Annambhaṭṭa, Tarkasaṅgraha (mūla)",
        author="अन्नम्भट्टः",
        schema="grantha_mula_text",
        target="darshana/nyaya/prakarana/tarkasangraha/mula",
        unit="sutra",
        # TEI transformation: one clean <p id="AnTs_N"> per sutra, no
        # commentary mixed in. Only covers the padartha-nirupana portion
        # (sutras 1-81, i.e. up to and including the "sapta padarthah"
        # summary sutra) -- the pramana-nirupana portion (pratyaksa /
        # anumana / upamana / sabda) that traditionally follows isn't
        # marked up with AnTs_ ids in this GRETIL file at all.
        urls=["https://gretil.sub.uni-goettingen.de/gretil/corpustei/"
              "transformations/html/sa_annaMbhatta-tarkasaMgraha.htm"]),

    "tarkasangraha_dipika": dict(
        name="Annambhaṭṭa, Tarkasaṅgraha with Dīpikā",
        author="अन्नम्भट्टः",
        schema="grantha_tika_text",
        tika_title="तर्कदीपिका",
        target="darshana/nyaya/prakarana/tarkasangraha/tika_dipika",
        unit="prakarana",
        # The _r.txt "raw" variant is NOT plain IAST -- it's Ronald
        # Emmerick's 8-bit WordPerfect encoding (diacritics live in the
        # 160-255 byte range per a table in its own header) and http_get's
        # forced UTF-8 decode mangles every accented character into U+FFFD.
        # _u.htm is the same content pre-converted to real UTF-8 by GRETIL
        # -- use that instead. Bundles Dipika (Annambhatta's own
        # auto-commentary) with Nilakantha's Prakasika and Balapriya mixed
        # in per-sutra; a cleaner per-tika split would need separate
        # sources for those layers.
        #
        # antsdi_u.htm only marks the padartha-nirupana span (AnTs_1..81,
        # same as tarkasangraha_mula above). The second URL is a different
        # edition (sanskritdocuments.org, ITRANS, Dipika only -- no
        # Prakasika/Balapriya) that covers the whole work across 8
        # adhyayas; its chapters 4-8 (pratyaksa/anumana/upamana/sabda +
        # the closing pramanya-vada discussion) fill the span the GRETIL
        # source doesn't reach. Chapters 1-3 of this second source
        # duplicate the padartha portion already covered more richly by
        # antsdi_u.htm, so the ITX-branch parser below skips them.
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/antsdi_u.htm",
              "https://sanskritdocuments.org/doc_z_misc_major_works/tarkasangraha.itx"]),

    "tattvacintamani_shabda": dict(
        name="Gaṅgeśa, Tattvacintāmaṇi — Śabdakhaṇḍa",
        author="गङ्गेशोपाध्यायः",
        schema="grantha_mula_text",
        target="darshana/nyaya/navya_nyaya/tattvacintamani/shabda_khanda/mula",
        unit="prakarana",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/gangtciu.htm"]),

    "nyayakusumanjali": dict(
        name="Udayana, Nyāyakusumāñjali",
        author="उदयनाचार्यः",
        schema="grantha_mula_text",
        target="darshana/nyaya/pramukha_prakarana/nyaya_kusumanjali/mula",
        unit="stabaka",
        urls=[BASE + f"1_sanskr/6_sastra/3_phil/nyaya/udnyku{n}u.htm" for n in range(1, 6)]),

    "mimamsasutra": dict(
        name="Jaimini, Mīmāṃsāsūtra",
        author="जैमिनिः",
        schema="grantha_mula_text",
        target="darshana/mimamsa/sutra_and_bhashya/mimamsa_sutra/mula",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/mimamsa/jaimsutu.htm"]),

    "shabarabhashya": dict(
        name="Mīmāṃsāsūtra with Śābarabhāṣya, adhyāyas 1–7",
        author="शबरस्वामी",
        schema="grantha_tika_text",
        tika_title="शाबरभाष्यम्",
        target="darshana/mimamsa/sutra_and_bhashya/mimamsa_sutra/shabara_bhashya",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/mimamsa/msbh1-7u.htm"]),

    "jaiminiya_nyayamala": dict(
        name="Mādhava, Jaiminīyanyāyamālāvistara",
        author="माधवाचार्यः",
        schema="grantha_mula_text",
        target="darshana/mimamsa/prakarana/jaiminiya_nyayamala/mula",
        unit="adhyaya",
        urls=[BASE + f"1_sanskr/6_sastra/3_phil/mimamsa/mjnya{n:02d}u.htm" for n in range(1, 13)],
        tolerate_missing=True),

    "shastradipika": dict(
        name="Pārthasārathi Miśra, Śāstradīpikā",
        author="पार्थसारथिमिश्रः",
        schema="grantha_mula_text",
        target="darshana/mimamsa/prakarana/shastra_dipika/mula",
        unit="adhyaya",
        urls=[BASE + "corpustei/transformations/html/sa_pArthasArathimizra-zAstradIpikA.htm"]),

    "shlokavarttika_kashika": dict(
        name="Kumārila's Ślokavārttika with Sucarita Miśra's Kāśikā",
        author="सुचरितमिश्रः",
        schema="grantha_tika_text",
        tika_title="काशिका",
        target="darshana/mimamsa/bhatta/shlokavarttika/tika_kashika",
        unit="adhyaya",
        urls=[BASE + "corpustei/transformations/html/sa_kumArila-mImAMsAzlokavArttika-comm.htm"]),
}

# GRETIL headers end at one of these markers; everything above is metadata we
# keep as provenance rather than text.
HEADER_END = re.compile(
    r"^\s*(?:TEXT\s*$|##+\s*$|\*{3,}\s*$|-{5,}\s*$|Text\s+of\s+the\s+edition)", re.M)
ATTRIB_LINE = re.compile(
    r"^(?:Input by|Contribution by|Contributed by|Based on|Text prepared|Encoded by|"
    r"Description:|Provided by|Sponsored by|Date of|Revisions?:).*$", re.I | re.M)

# Section headings in GRETIL śāstra files. Deliberately broad: these files come
# from many different contributors and no single convention holds across them.
SECTION_PATTERNS = [
    re.compile(r"^\s*(?:atha\s+)?(?P<label>[a-zA-Zāīūṛṝḷṅñṭḍṇśṣḥṃ'-]+)?\s*"
               r"(?P<n1>\d+)[.,](?P<n2>\d+)(?:[.,](?P<n3>\d+))?\s*$", re.M),
    re.compile(r"^\s*//\s*(?P<label>[A-Za-z]{2,12})_(?P<n1>\d+)[.,](?P<n2>\d+)"
               r"(?:[.,](?P<n3>\d+))?\s*//\s*$", re.M),
    re.compile(r"^\s*\[?(?P<label>adhyāya|āhnika|stabaka|pariccheda|prakaraṇa|pāda|khaṇḍa)"
               r"\s*(?P<n1>\d+)\]?\s*$", re.M | re.I),
]
NOISE = re.compile(r"[\\^~]|_{3,}")


def split_header(raw):
    """Return (attribution_text, body). Never loses the body if no marker exists."""
    match = HEADER_END.search(raw)
    head, body = (raw[:match.start()], raw[match.end():]) if match else ("", raw)
    if not body.strip():
        head, body = "", raw
    attribution = " | ".join(
        re.sub(r"\s+", " ", line).strip()
        for line in ATTRIB_LINE.findall(head or raw[:4000])
    )
    return attribution[:1200], body


def find_sections(body):
    """Yield (label, number_tuple, start, end) for whichever pattern matches most."""
    best = []
    for pattern in SECTION_PATTERNS:
        hits = list(pattern.finditer(body))
        if len(hits) > len(best):
            best = hits
    if not best:
        return []
    spans = []
    for index, match in enumerate(best):
        end = best[index + 1].start() if index + 1 < len(best) else len(body)
        numbers = tuple(int(g) for g in (match.group("n1"), match.group("n2"),
                                         match.groupdict().get("n3")) if g)
        spans.append(((match.groupdict().get("label") or "").strip(), numbers,
                      match.end(), end))
    return spans


def clean(chunk):
    chunk = NOISE.sub(" ", chunk)
    chunk = re.sub(r"\s+", " ", chunk).strip(" /|")
    return chunk.strip()


def parse(raw, spec):
    """GRETIL file -> DGE items. One item per section; whole file if unsegmented."""
    attribution, body = split_header(raw)
    body = to_text(body) if "<" in body[:2000] else body
    unit = spec.get("unit", "section")
    items = []

    for label, numbers, start, end in find_sections(body):
        text = clean(body[start:end])
        if len(text) < 12:
            continue
        ref = ".".join(str(n) for n in numbers) or str(len(items) + 1)
        items.append(build_item(spec, f"{unit}_{ref.replace('.', '_')}",
                                f"{spec['name']}, {unit} {ref}", text, attribution,
                                section=label or unit))

    if not items:
        # No recognisable segmentation — keep the text rather than dropping it,
        # and flag it so a human can add a pattern.
        text = clean(body)
        if len(text) >= 12:
            items.append(build_item(spec, f"{unit}_01", spec["name"], text, attribution,
                                    section=unit, unsegmented=True))
    return items, attribution


# --- Tarkasangraha: dedicated parsers -----------------------------------
# Neither source uses the "// ABBR_n.n //" / heading-driven conventions
# SECTION_PATTERNS targets, so they get their own marker regexes instead
# of going through find_sections().

_TEI_SUTRA = re.compile(r'<p id="AnTs_(\d+)">(.*?)</p>', re.S)


def _tei_clean(inner):
    inner = re.sub(r'<span class="ref">.*?</span>', "", inner, flags=re.S)
    inner = re.sub(r"<[^>]+>", " ", inner)
    inner = html.unescape(inner)
    return clean(inner)


def parse_tarkasangraha_mula(raw, spec):
    items = []
    for match in _TEI_SUTRA.finditer(raw):
        num, inner = match.groups()
        text = _tei_clean(inner)
        if not text:
            continue
        items.append(build_item(spec, f"sutra_{num}", f"AnTs_{num}", text, "",
                                 section="sutra"))
    return items, ""


# AnTs_1ab / AnTs_1cd (pada-split mangala verse), AnTs_10[1] / AnTs_10[2]
# (a long sutra split into sub-parts), AnTs_2 .. AnTs_81 (the common case).
_DIPIKA_MARKER = re.compile(r"AnTs_(?P<num>\d+)(?:\[\d+\])?[a-z]{0,4}")
_DIPIKA_START = "maṅgalavādaḥ"  # first heading of the actual text, past the Balapriya preface
# A single sutra's own commentary runs a few thousand characters at most
# (see the longest *bounded* item, ~59k for a dense one); past this a
# "no next marker found" tail is swallowing unrelated later material
# rather than legitimately belonging to the last marked sutra.
_TAIL_CAP = 60_000


def parse_tarkasangraha_dipika(raw, spec):
    # Two different editions share this spec's urls list (see the comment
    # on tarkasangraha_dipika above) -- route by a marker only the ITX one has.
    if "\\begin{document}" in raw[:4000]:
        return _parse_dipika_itx(raw, spec)
    return _parse_dipika_html(raw, spec)


def _parse_dipika_html(raw, spec):
    start = raw.find(_DIPIKA_START)
    text = to_text(raw[start:] if start >= 0 else raw)
    matches = list(_DIPIKA_MARKER.finditer(text))

    # A marker only starts a new item the first time its number is reached
    # in sequence -- ab/cd pairs and [1]/[2] sub-parts share their sutra's
    # number and fold into that same item instead of starting new ones.
    boundaries, expected = [], 1
    for match in matches:
        if int(match.group("num")) == expected:
            boundaries.append(match)
            expected += 1

    items = []
    for index, match in enumerate(boundaries):
        num = match.group("num")
        chunk_start = match.end()
        chunk_end = boundaries[index + 1].start() if index + 1 < len(boundaries) else len(text)
        chunk = _DIPIKA_MARKER.sub(" ", text[chunk_start:chunk_end])
        body = clean(chunk)
        if not body:
            continue
        # The source only tags the padartha-nirupana portion (sutras
        # 1-81) with AnTs_ markers; everything past the last boundary is
        # the pramana-nirupana portion (pratyaksa/anumana/upamana/sabda
        # khandas) running on with no per-sutra markers at all. That
        # remainder is covered properly, chapter by chapter, by
        # _parse_dipika_itx below -- cap this tail rather than dump it
        # (previously ~440k chars) wholesale under sutra 81.
        is_tail = index == len(boundaries) - 1
        if is_tail:
            body = body[:_TAIL_CAP]
        reference = (f"AnTs_{num} onward (unsegmented, truncated -- see "
                      "the adhyaya-numbered items below for the rest)"
                      if is_tail else f"AnTs_{num}")
        items.append(build_item(spec, f"prakarana_{num}", reference, body, "",
                                 section="prakarana", unsegmented=is_tail))
    return items, ""


# sanskritdocuments.org edition: \section{atha <ordinal>o.adhyAya} per
# chapter, "-|| N ||"-style verse-end markers whose numbering sometimes
# restarts per chapter and sometimes continues across a chapter boundary
# (e.g. adhyaya 3 ends at 30, adhyaya 4 continues 31..40) -- always use
# each marker's own printed number rather than assuming a restart.
_ITX_SECTION = re.compile(r"\\section\{([^}]*)\}")
_ITX_VEND = re.compile(r"\|\|\s*(\d+)\s*\|\|")
_ITX_NOISE = re.compile(r"##\(##|##\)##|##|\\-")
_ITX_QUOTE = re.compile(r"\\[lr]dq\{\}")  # itrans package's left/right curly-quote macros


def _itx_clean(chunk):
    chunk = _ITX_QUOTE.sub('"', chunk)
    chunk = _ITX_NOISE.sub("", chunk)
    chunk = chunk.replace("\\,", ",")  # itrans escaped-comma (avoids ITRANS reparsing the comma)
    # Any other stray \command{...} or \command is layout markup (itrans
    # package macros), never real Sanskrit -- confirmed for real: without
    # this, "Encoded by ashish\_{}chandr70..." and similar credits-block
    # noise near the footer survive into transliterated output as garbage.
    chunk = re.sub(r"\\[a-zA-Z]+\{[^}]*\}", " ", chunk)
    chunk = re.sub(r"\\[a-zA-Z]+", " ", chunk)
    chunk = re.sub(r"\s+", " ", chunk).strip(" |")
    return chunk.strip()


def _parse_dipika_itx(raw, spec):
    sections = list(_ITX_SECTION.finditer(raw))
    # The credits footer ("Encoded by ...") precedes \end{document} and
    # isn't real text -- stop there, not at \end{document} itself.
    end_doc = raw.find("Encoded by")
    if end_doc < 0:
        end_doc = raw.find("\\end{document}")
    if end_doc < 0:
        end_doc = len(raw)

    items = []
    # Chapters 1-3 (padartha-nirupana) duplicate what antsdi_u.htm already
    # covers, with a richer Dipika+Prakasika+Balapriya commentary -- only
    # take chapters 4 onward (pratyaksa/anumana/upamana/sabda + the
    # closing epistemology discussion), which antsdi_u.htm's tail doesn't
    # reach with any real segmentation.
    for chapter_index in range(3, len(sections)):
        chapter_num = chapter_index + 1
        body_start = sections[chapter_index].end()
        body_end = sections[chapter_index + 1].start() if chapter_index + 1 < len(sections) else end_doc
        body = raw[body_start:body_end]
        marks = list(_ITX_VEND.finditer(body))

        if not marks:
            # Chapter 8 (pramanya-vada discussion) has no verse markers at
            # all -- keep it as one item rather than dropping it.
            text = itrans_to_iast(_itx_clean(body))
            if text:
                items.append(build_item(
                    spec, f"adhyaya_{chapter_num}", f"Tarkasaṅgraha {chapter_num} (no sutra markers in source)",
                    text, "", section="adhyaya", unsegmented=True))
            continue

        prev_end = 0
        for mark_index, mark in enumerate(marks):
            num = mark.group(1)
            chunk = body[prev_end:mark.end()]
            prev_end = mark.end()
            text = itrans_to_iast(_itx_clean(chunk))
            if not text:
                continue
            # Only the first marker in a chapter is a clean sutra-only
            # boundary; later ones open with the tail of the previous
            # sutra's commentary before this one's own root text, for the
            # same reason as the antsdi_u.htm parser above (no typographic
            # break between running commentary and the next root verse).
            items.append(build_item(
                spec, f"adhyaya_{chapter_num}_{num}", f"Tarkasaṅgraha {chapter_num}.{num}",
                text, "", section="adhyaya"))
    return items, ""


def build_item(spec, item_id, reference, iast_text, attribution, section="",
               unsegmented=False):
    item = {
        "id": item_id,
        "reference": reference,
        "section": section,
        "sanskrit_text": iast_to_dev(iast_text),
        "iast_text": iast_text,
        "artha": "",
        "notes": "",
        "tags": (["unsegmented"] if unsegmented else []),
        "references": [],
        "audio": [],
        "source": {"site": "gretil.sub.uni-goettingen.de", "attribution": attribution},
    }
    if spec["schema"] == "grantha_tika_text" and spec.get("tika_title"):
        item["tika_title"] = spec["tika_title"]
    return item


# ids with a dedicated parser instead of the generic heading-driven one
_CUSTOM_PARSERS = {
    "tarkasangraha_mula": parse_tarkasangraha_mula,
    "tarkasangraha_dipika": parse_tarkasangraha_dipika,
}


def run(tid):
    spec = DARSHANA_GRETIL[tid]
    chunks = []
    for url in spec["urls"]:
        try:
            chunks.append(http_get(url))
        except Exception as exc:
            if not spec.get("tolerate_missing"):
                raise
            print(f"  skip {url}: {exc}", file=sys.stderr)
    if not chunks:
        raise SystemExit(f"{tid}: no source fetched")

    parse_fn = _CUSTOM_PARSERS.get(tid, parse)
    items, attribution = [], ""
    for raw in chunks:
        part, attr = parse_fn(raw, spec)
        items.extend(part)
        attribution = attribution or attr

    # Ids must be unique within a layer even when several URLs contribute.
    seen = {}
    for item in items:
        base = item["id"]
        seen[base] = seen.get(base, 0) + 1
        if seen[base] > 1:
            item["id"] = f"{base}_{seen[base]}"

    note = ("GRETIL. THIS GRETIL TEXT FILE IS FOR REFERENCE PURPOSES ONLY! "
            "COPYRIGHT AND TERMS OF USAGE AS FOR SOURCE FILE. " + attribution).strip()
    write_grantha(spec["target"], spec["schema"], spec["author"], items)
    _annotate(spec, note)
    print(f"{tid}: {len(items)} item(s) -> {spec['target']}")


def _annotate(spec, note):
    """write_grantha only writes schema/default_author/items — add provenance."""
    import json
    import os
    from common import data_base
    path = os.path.join(data_base(), spec["target"], "data.json")
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
    payload["source_url"] = spec["urls"][0]
    payload["source_note"] = note
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=1)


if __name__ == "__main__":
    if "--list" in sys.argv:
        for key, spec in DARSHANA_GRETIL.items():
            print(f"{key:28} {spec['name']}\n{'':28} -> {spec['target']}")
    elif len(sys.argv) == 2:
        run(sys.argv[1])
    else:
        raise SystemExit("usage: darshana_gretil.py <id> | --list")
