"""GRETIL importer for the Darśana branch (Nyāya, Vaiśeṣika, Mīmāṃsā).

Kept separate from importers/gretil.py because the śāstra texts are structurally
unlike the smṛti/kāvya ones that module handles. Those are verse corpora with a
'// ABBR_canto.verse //' marker on every śloka. Nyāya and Mīmāṃsā are prose:
sūtra + bhāṣya + vārttika running together, segmented by section headings
(adhikaraṇa, āhnika, stabaka, adhyāya-pāda) rather than by verse number. So the
unit here is a SECTION, not a verse, and the parser is heading-driven.

Targets are the layer folders generated by tools/darshanas/scaffold_darshanas.py.
The scaffolder must have run first — this importer fills stubs, it does not
create them.

GRETIL is romanised IAST, not Devanagari; transliteration is a pipeline step
(common.iast_to_dev). Every file carries "COPYRIGHT AND TERMS OF USAGE AS FOR
SOURCE FILE", so the header's source-attribution block is captured verbatim into
source_note rather than discarded.

Run:  python importers/dispatch.py <id>
      python importers/darshana_gretil.py --list
"""

import re
import sys

from common import http_get, to_text, iast_to_dev, write_grantha

BASE = "https://gretil.sub.uni-goettingen.de/gretil/"

# id -> spec. `target` is a path under dge/data/ produced by the scaffolder.
DARSHANA_GRETIL = {
    "nyayasutra_bhashya": dict(
        name="Nyāyasūtra with Vātsyāyana's Bhāṣya",
        author="पक्षिलस्वामिवात्स्यायनः",
        schema="grantha_tika_text",
        tika_title="न्यायभाष्यम्",
        target="darshana/nyaya/prachina_nyaya/nyaya_sutra/bhashya_vatsyayana",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/nysvbh1u.htm"]),

    "nyayasutra_tatparyatika": dict(
        name="Nyāyasūtra with Vācaspati Miśra's Tātparyaṭīkā",
        author="वाचस्पतिमिश्रः",
        schema="grantha_tika_text",
        tika_title="न्यायवार्त्तिकतात्पर्यटीका",
        target="darshana/nyaya/prachina_nyaya/nyaya_sutra/tatparya_tika",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/nystik_u.htm"]),

    "tarkasangraha_dipika": dict(
        name="Annambhaṭṭa, Tarkasaṅgraha with Dīpikā",
        author="अन्नम्भट्टः",
        schema="grantha_tika_text",
        tika_title="तर्कदीपिका",
        target="darshana/nyaya/prakarana/tarkasangraha/tika_dipika",
        unit="prakarana",
        # the _r.txt raw variant is cleaner than the _u.htm rendering
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/antsdi_r.txt"]),

    "tattvacintamani_shabda": dict(
        name="Gaṅgeśa, Tattvacintāmaṇi — Śabdakhaṇḍa",
        author="गङ्गेशोपाध्यायः",
        schema="grantha_mula_text",
        target="darshana/nyaya/navya_nyaya/tattvacintamani/shabda_khanda/mula",
        unit="prakarana",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/nyaya/gangtciu.htm"]),

    "nyayakusumanjali": dict(
        name="Udayana, Nyāyakusumāñjali",
        author="उदयनाचार्यः",
        schema="grantha_mula_text",
        target="darshana/nyaya/pramukha_prakarana/nyaya_kusumanjali/mula",
        unit="stabaka",
        urls=[BASE + f"1_sanskr/6_sastra/3_phil/nyaya/udnyku{n}u.htm" for n in range(1, 6)]),

    "mimamsasutra": dict(
        name="Jaimini, Mīmāṃsāsūtra",
        author="जैमिनिः",
        schema="grantha_mula_text",
        target="darshana/mimamsa/sutra_and_bhashya/mimamsa_sutra/mula",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/mimamsa/jaimsutu.htm"]),

    "shabarabhashya": dict(
        name="Mīmāṃsāsūtra with Śābarabhāṣya, adhyāyas 1–7",
        author="शबरस्वामी",
        schema="grantha_tika_text",
        tika_title="शाबरभाष्यम्",
        target="darshana/mimamsa/sutra_and_bhashya/mimamsa_sutra/shabara_bhashya",
        unit="adhyaya",
        urls=[BASE + "1_sanskr/6_sastra/3_phil/mimamsa/msbh1-7u.htm"]),

    "jaiminiya_nyayamala": dict(
        name="Mādhava, Jaiminīyanyāyamālāvistara",
        author="माधवाचार्यः",
        schema="grantha_mula_text",
        target="darshana/mimamsa/prakarana/jaiminiya_nyayamala/mula",
        unit="adhyaya",
        urls=[BASE + f"1_sanskr/6_sastra/3_phil/mimamsa/mjnya{n:02d}u.htm" for n in range(1, 13)],
        tolerate_missing=True),

    "shastradipika": dict(
        name="Pārthasārathi Miśra, Śāstradīpikā",
        author="पार्थसारथिमिश्रः",
        schema="grantha_mula_text",
        target="darshana/mimamsa/prakarana/shastra_dipika/mula",
        unit="adhyaya",
        urls=[BASE + "corpustei/transformations/html/sa_pArthasArathimizra-zAstradIpikA.htm"]),

    "shlokavarttika_kashika": dict(
        name="Kumārila's Ślokavārttika with Sucarita Miśra's Kāśikā",
        author="सुचरितमिश्रः",
        schema="grantha_tika_text",
        tika_title="काशिका",
        target="darshana/mimamsa/bhatta/shlokavarttika/tika_kashika",
        unit="adhyaya",
        urls=[BASE + "corpustei/transformations/html/sa_kumArila-mImAMsAzlokavArttika-comm.htm"]),
}

# GRETIL headers end at one of these markers; everything above is metadata we
# keep as provenance rather than text.
HEADER_END = re.compile(
    r"^\s*(?:TEXT\s*$|##+\s*$|\*{3,}\s*$|-{5,}\s*$|Text\s+of\s+the\s+edition)", re.M)
ATTRIB_LINE = re.compile(
    r"^(?:Input by|Contribution by|Contributed by|Based on|Text prepared|Encoded by|"
    r"Description:|Provided by|Sponsored by|Date of|Revisions?:).*$", re.I | re.M)

# Section headings in GRETIL śāstra files. Deliberately broad: these files come
# from many different contributors and no single convention holds across them.
SECTION_PATTERNS = [
    re.compile(r"^\s*(?:atha\s+)?(?P<label>[a-zA-Zāīūṛṝḷṅñṭḍṇśṣḥṃ'-]+)?\s*"
               r"(?P<n1>\d+)[.,](?P<n2>\d+)(?:[.,](?P<n3>\d+))?\s*$", re.M),
    re.compile(r"^\s*//\s*(?P<label>[A-Za-z]{2,12})_(?P<n1>\d+)[.,](?P<n2>\d+)"
               r"(?:[.,](?P<n3>\d+))?\s*//\s*$", re.M),
    re.compile(r"^\s*\[?(?P<label>adhyāya|āhnika|stabaka|pariccheda|prakaraṇa|pāda|khaṇḍa)"
               r"\s*(?P<n1>\d+)\]?\s*$", re.M | re.I),
]
NOISE = re.compile(r"[\\^~]|_{3,}")


def split_header(raw):
    """Return (attribution_text, body). Never loses the body if no marker exists."""
    match = HEADER_END.search(raw)
    head, body = (raw[:match.start()], raw[match.end():]) if match else ("", raw)
    if not body.strip():
        head, body = "", raw
    attribution = " | ".join(
        re.sub(r"\s+", " ", line).strip()
        for line in ATTRIB_LINE.findall(head or raw[:4000])
    )
    return attribution[:1200], body


def find_sections(body):
    """Yield (label, number_tuple, start, end) for whichever pattern matches most."""
    best = []
    for pattern in SECTION_PATTERNS:
        hits = list(pattern.finditer(body))
        if len(hits) > len(best):
            best = hits
    if not best:
        return []
    spans = []
    for index, match in enumerate(best):
        end = best[index + 1].start() if index + 1 < len(best) else len(body)
        numbers = tuple(int(g) for g in (match.group("n1"), match.group("n2"),
                                         match.groupdict().get("n3")) if g)
        spans.append(((match.groupdict().get("label") or "").strip(), numbers,
                      match.end(), end))
    return spans


def clean(chunk):
    chunk = NOISE.sub(" ", chunk)
    chunk = re.sub(r"\s+", " ", chunk).strip(" /|")
    return chunk.strip()


def parse(raw, spec):
    """GRETIL file -> DGE items. One item per section; whole file if unsegmented."""
    attribution, body = split_header(raw)
    body = to_text(body) if "<" in body[:2000] else body
    unit = spec.get("unit", "section")
    items = []

    for label, numbers, start, end in find_sections(body):
        text = clean(body[start:end])
        if len(text) < 12:
            continue
        ref = ".".join(str(n) for n in numbers) or str(len(items) + 1)
        items.append(build_item(spec, f"{unit}_{ref.replace('.', '_')}",
                                f"{spec['name']}, {unit} {ref}", text, attribution,
                                section=label or unit))

    if not items:
        # No recognisable segmentation — keep the text rather than dropping it,
        # and flag it so a human can add a pattern.
        text = clean(body)
        if len(text) >= 12:
            items.append(build_item(spec, f"{unit}_01", spec["name"], text, attribution,
                                    section=unit, unsegmented=True))
    return items, attribution


def build_item(spec, item_id, reference, iast_text, attribution, section="",
               unsegmented=False):
    item = {
        "id": item_id,
        "reference": reference,
        "section": section,
        "sanskrit_text": iast_to_dev(iast_text),
        "iast_text": iast_text,
        "artha": "",
        "notes": "",
        "tags": (["unsegmented"] if unsegmented else []),
        "references": [],
        "audio": [],
        "source": {"site": "gretil.sub.uni-goettingen.de", "attribution": attribution},
    }
    if spec["schema"] == "grantha_tika_text" and spec.get("tika_title"):
        item["tika_title"] = spec["tika_title"]
    return item


def run(tid):
    spec = DARSHANA_GRETIL[tid]
    chunks = []
    for url in spec["urls"]:
        try:
            chunks.append(http_get(url))
        except Exception as exc:
            if not spec.get("tolerate_missing"):
                raise
            print(f"  skip {url}: {exc}", file=sys.stderr)
    if not chunks:
        raise SystemExit(f"{tid}: no source fetched")

    items, attribution = [], ""
    for raw in chunks:
        part, attr = parse(raw, spec)
        items.extend(part)
        attribution = attribution or attr

    # Ids must be unique within a layer even when several URLs contribute.
    seen = {}
    for item in items:
        base = item["id"]
        seen[base] = seen.get(base, 0) + 1
        if seen[base] > 1:
            item["id"] = f"{base}_{seen[base]}"

    note = ("GRETIL. THIS GRETIL TEXT FILE IS FOR REFERENCE PURPOSES ONLY! "
            "COPYRIGHT AND TERMS OF USAGE AS FOR SOURCE FILE. " + attribution).strip()
    write_grantha(spec["target"], spec["schema"], spec["author"], items)
    _annotate(spec, note)
    print(f"{tid}: {len(items)} item(s) -> {spec['target']}")


def _annotate(spec, note):
    """write_grantha only writes schema/default_author/items — add provenance."""
    import json
    import os
    from common import data_base
    path = os.path.join(data_base(), spec["target"], "data.json")
    with open(path, encoding="utf-8") as handle:
        payload = json.load(handle)
    payload["source_url"] = spec["urls"][0]
    payload["source_note"] = note
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=1)


if __name__ == "__main__":
    if "--list" in sys.argv:
        for key, spec in DARSHANA_GRETIL.items():
            print(f"{key:28} {spec['name']}\n{'':28} -> {spec['target']}")
    elif len(sys.argv) == 2:
        run(sys.argv[1])
    else:
        raise SystemExit("usage: darshana_gretil.py <id> | --list")
