#!/usr/bin/env python3
"""Extract People / Mathas / Places entity indexes from parampara.json.

dge/guru-parampara/data/parampara.json is 215 person-nodes, each carrying a
matha code and a free-text place string inline. The project's own longer-term
plan (see the DGE Global Renderer / Guru Parampara architecture discussion)
wants Mathas and Places as first-class entities of their own -- with a
current pontiff, branch contacts, GPS, tirtha-prasada availability, and their
own admin edit pages eventually. This script is step one, additive only: it
reads parampara.json (never writes to it) and emits three small index files
alongside it. The existing 2D/3D/tracker views keep reading parampara.json
directly and are completely unaffected by this running.

Deliberately NOT invented here: current pontiff, contact details, GPS
coordinates, branch lists, tirtha-prasada availability. Fabricating any of
that for a real living lineage/institution would be a real accuracy and
trust problem, not a placeholder worth having -- so every such field is
written out explicitly as null with a comment key explaining why, ready for
a human editor (via a future admin page) to fill in from a verified source,
never guessed by this script or by an LLM.

Usage: python3 tools/build_guru_parampara_entities.py
Re-run any time parampara.json changes; output is fully deterministic from
its input (sorted keys, stable ids) so a re-run with no source change is a
no-op diff.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "dge" / "guru-parampara" / "data" / "parampara.json"
OUT_DIR = SRC.parent


def slugify(text):
    s = text.strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-") or "unknown"


def build_people(nodes):
    people = []
    for n in nodes:
        people.append({
            "id": n["id"],
            "name": n.get("name", ""),
            "titles": n.get("titles", []),
            "period": n.get("period", ""),
            "birth": n.get("b", ""),
            "death": n.get("d", ""),
            "role": n.get("role", ""),
            "matha": n.get("matha", ""),
            "confidence": n.get("confidence", ""),
        })
    people.sort(key=lambda p: p["id"])
    return people


def build_mathas(nodes, matha_labels):
    by_code = {}
    for n in nodes:
        code = n.get("matha")
        if not code:
            continue
        by_code.setdefault(code, []).append(n["id"])

    mathas = []
    # every labelled matha, even one with zero nodes today, plus any matha
    # code that appears on a node but has no label (so nothing referenced by
    # the source data silently disappears from this index)
    all_codes = set(matha_labels) | set(by_code)
    for code in sorted(all_codes):
        mathas.append({
            "id": code,
            "label": matha_labels.get(code, code),
            "people": sorted(by_code.get(code, [])),
            # Not fabricated -- see this file's module docstring. Fill in
            # from a verified source via a future admin edit page.
            "current_pontiff": None,
            "branches": [],
            "contact": None,
            "gps": None,
            "tirtha_prasada": None,
        })
    return mathas


def build_places(nodes):
    by_slug = {}
    for n in nodes:
        place = (n.get("place") or "").strip()
        if not place:
            continue
        slug = slugify(place)
        entry = by_slug.setdefault(slug, {"id": slug, "label": place, "people": []})
        entry["people"].append(n["id"])

    places = list(by_slug.values())
    for p in places:
        p["people"].sort()
    places.sort(key=lambda p: p["id"])
    for p in places:
        # Not fabricated -- see this file's module docstring.
        p["gps"] = None
    return places


def main():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    nodes = data["nodes"]
    matha_labels = data.get("matha_labels", {})

    people = build_people(nodes)
    mathas = build_mathas(nodes, matha_labels)
    places = build_places(nodes)

    write(OUT_DIR / "people.json", {
        "_readme": [
            "Generated by tools/build_guru_parampara_entities.py from",
            "dge/guru-parampara/data/parampara.json -- do not hand-edit this file,",
            "edit parampara.json and re-run the script instead. One entry per",
            "person-node in parampara.json (id matches), stripped down to the",
            "identity fields a People/Authors index needs. matha is that",
            "person's matha code -- see mathas.json for the matha's own entry.",
        ],
        "people": people,
    })
    write(OUT_DIR / "mathas.json", {
        "_readme": [
            "Generated by tools/build_guru_parampara_entities.py from",
            "dge/guru-parampara/data/parampara.json -- do not hand-edit the id/",
            "label/people fields (re-run the script after editing parampara.json",
            "instead). current_pontiff/branches/contact/gps/tirtha_prasada are",
            "the exception: left null on purpose, never guessed by this script,",
            "meant to be filled in by a human editor from a verified source via",
            "a future admin edit page for mathas.",
        ],
        "mathas": mathas,
    })
    write(OUT_DIR / "places.json", {
        "_readme": [
            "Generated by tools/build_guru_parampara_entities.py from",
            "dge/guru-parampara/data/parampara.json -- do not hand-edit the id/",
            "label/people fields (re-run the script after editing parampara.json",
            "instead). One entry per distinct place string referenced by a",
            "person-node's `place` field (deduplicated, not geocoded). gps is",
            "left null on purpose -- not fabricated by this script, meant to be",
            "filled in by a human editor via a future admin edit page.",
        ],
        "places": places,
    })

    print(f"people.json: {len(people)} people")
    print(f"mathas.json: {len(mathas)} mathas")
    print(f"places.json: {len(places)} places")


def write(path, obj):
    # 2-space indent to match parampara.json's own formatting in this folder.
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
